### PR TITLE
Catch error when failing to properly read README.rst.

### LINKED ISSUE #2: Produces an error when there is no README.rst listed in the input files
```
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
```

This error is resolved by commenting out the section in publish.js that attempts to look at the readme file. The issue for me was that I was testing and scanning a subset of the files in the project to test out the plugin - it broke every time, because there was no README.rst in the project.

Suggested fix: Add a try, catch block around the part where you are reading the README file, as the lodash find is not always finding what you think it should be.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #2

### CODE REVIEW

**Comment by rtibbles** [comment]
@oliamb Any chance of getting this merged and published to npm? I'd really like to use this in a project I am working on, but it is currently unusable because of this bug.

**Comment by oliamb** [comment]
Oops. I'm sorry for the delay.

**Comment by oliamb** [comment]
Just published v0.0.4 including your fix. This project is brand new so I'm willing to accept lots of contributions like this one ;-)

**Comment by rtibbles** [comment]
Weird, not seeing v0.0.4 on npm.

**Comment by oliamb** [comment]
I'm not in front of a computer right now. I will have a look in a couple of hours. Sorry for that.

Envoyé de mon iPhone

**Comment by oliamb** [comment]
Done, it has been published to a private repo instead...

**Comment by rtibbles** [comment]
Awesome, thanks!

**Pull request merged**
